# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VidarAPI.Model.Asset do
  @moduledoc """
  Entity representing asset
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :currency,
    :assetClass,
    :assetSubClass,
    :investmentType,
    :description,
    :quotationFactor,
    :interestRate,
    :maturityDate,
    :riskScore
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :name => String.t() | nil,
          :currency => String.t() | nil,
          :assetClass => String.t() | nil,
          :assetSubClass => String.t() | nil,
          :investmentType => String.t() | nil,
          :description => String.t() | nil,
          :quotationFactor => float() | nil,
          :interestRate => float() | nil,
          :maturityDate => Date.t() | nil,
          :riskScore => integer() | nil
        }

  alias VidarAPI.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:maturityDate, :date, nil)
  end
end
