# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VidarAPI.Model.PortfolioAum do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :portfolioDailyMetricsId,
    :statementDate,
    :netAmount,
    :grossAmount,
    :currency
  ]

  @type t :: %__MODULE__{
          :portfolioDailyMetricsId => integer() | nil,
          :statementDate => Date.t(),
          :netAmount => float() | nil,
          :grossAmount => float() | nil,
          :currency => String.t() | nil
        }

  alias VidarAPI.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:statementDate, :date, nil)
  end
end
