# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VidarAPI.Model.PositionValue do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :amount,
    :currency,
    :fxRateDate,
    :fxRateFrom,
    :fxRateTo,
    :fxRate,
    :fxRateSource
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :amount => float() | nil,
    :currency => String.t | nil,
    :fxRateDate => String.t | nil,
    :fxRateFrom => String.t | nil,
    :fxRateTo => String.t | nil,
    :fxRate => float() | nil,
    :fxRateSource => String.t | nil
  }

  def decode(value) do
    value
  end
end

