# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VidarAPI.Model.PositionPerformance do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :positionId,
    :ytdMarket,
    :mtdMarket,
    :ytdCurrencyEffect,
    :mtdCurrencyEffect,
    :ytdPerformance,
    :mtdPerformance
  ]

  @type t :: %__MODULE__{
          :positionId => integer() | nil,
          :ytdMarket => float() | nil,
          :mtdMarket => float() | nil,
          :ytdCurrencyEffect => float() | nil,
          :mtdCurrencyEffect => float() | nil,
          :ytdPerformance => float() | nil,
          :mtdPerformance => float() | nil
        }

  def decode(value) do
    value
  end
end
