# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VidarAPI.Model.PositionPnl do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :positionId,
    :portfolioId,
    :totalPnL,
    :totalPnLPercentage,
    :marketPnL,
    :marketPnLPercentage,
    :pnLCurrencyEffect,
    :totalPnLWithCashflow,
    :totalPnLWithCashflowPercentage,
    :cumulativeCashflow
  ]

  @type t :: %__MODULE__{
    :positionId => integer() | nil,
    :portfolioId => integer() | nil,
    :totalPnL => float() | nil,
    :totalPnLPercentage => float() | nil,
    :marketPnL => float() | nil,
    :marketPnLPercentage => float() | nil,
    :pnLCurrencyEffect => float() | nil,
    :totalPnLWithCashflow => float() | nil,
    :totalPnLWithCashflowPercentage => float() | nil,
    :cumulativeCashflow => float() | nil
  }

  def decode(value) do
    value
  end
end

