# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VidarAPI.Model.TransactionODataResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :context,
    :value
  ]

  @type t :: %__MODULE__{
    :context => String.t | nil,
    :value => VidarAPI.Model.Transaction.t
  }

  alias VidarAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:value, :struct, VidarAPI.Model.Transaction)
  end
end

